version: '3.8'
services:
  # app:
  #   build: ./
  #   container_name: "typescript_service"
  #   restart: unless-stopped
  #   working_dir: /var/www
  #   volumes:
  #     - ./src:/var/www
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - typescript

  db:
    image: mysql:8.0
    container_name: "typescript_db"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}   
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d
    networks:
      - typescript

networks:
  typescript:
    driver: bridge